parameters:
# xrowmetadata
    xrow_metadata_types.xrowmetadata.class: xrow\XrowMetadataBundle\FieldType\XrowMetadata\Type
    xrow_metadata_types.xrowmetadata.converter.class: xrow\XrowMetadataBundle\FieldType\XrowMetadata\XrowMetadataConverter
    xrow_metadata_types.xrowmetadata.externalStorage.class: xrow\XrowMetadataBundle\FieldType\XrowMetadata\XrowMetadataStorage
    xrow_metadata_types.xrowmetadata.storage_gateway.class: xrow\XrowMetadataBundle\FieldType\XrowMetadata\XrowMetadataStorage\Gateway\LegacyStorage

services:
# xrowmetadata
    xrow_metadata_types.xrowmetadata:
        class: %xrow_metadata_types.xrowmetadata.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: xrowmetadata}
    xrow_metadata_types.xrowmetadata.converter:
        class: %xrow_metadata_types.xrowmetadata.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: xrowmetadata}
    xrow_metadata_types.xrowmetadata.externalStorage:
        class: %xrow_metadata_types.xrowmetadata.externalStorage.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: xrowmetadata}
    xrow_metadata_types.xrowmetadata.storage_gateway:
        class: %xrow_metadata_types.xrowmetadata.storage_gateway.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: xrowmetadata, identifier: LegacyStorage}